language: python

branches:
  except:
    - dependabot
    - dependabot/*
  only:
    - master
    - stable

jobs:
  include:
    - stage: 'Deploy'
      name: 'Deploy test site'
      script:
        .travis/deploy.sh
