site_name: Ugla Style Guide
site_description: O projeto Ugla foi desenvolvido com o objetivo de minimizar esforços no desenvolvimento FrontEnd de sistemas.
site_author: Regivaldo Silva 
site_url: https://ugla.dev

repo_name: ciandt/ugla-docs
repo_url: https://github.com/ciandt/ugla-docs
edit_uri: ''

google_analytics: ['UA-152823777-1', 'ugla.dev']

theme:
  name: 'material'
  language: pt
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: 'assets/images/favicon.ico'
  favicon: 'assets/images/favicon.ico'

nav:
  - Getting started: 'index.md'
  - Colaborando:
    - Colaboradores: 'collaborate/colabs.md'
    - Colaborar com a documentação: 'collaborate/doc.md'
    - Colaborar com a biblioteca: 'collaborate/lib.md'
    - Trello e Issues: 'collaborate/tasks.md'
  - CSS:
    - Color: css/color.md
    - Mixins: css/mixins.md
    - Table: css/table.md
    - Typography: css/typography.md
  - Ugla Rules: 'rules/index.md'
  - Páginas: 'pages/index.md'
  - Componentes:
    - Header:
      - Home: 'components/header/index.md'
      - Brand: 'components/header/brand.md'
      - People Card: 'components/header/peoplecard.md'
    - Aide: 'components/aside.md'
    - Banner: 'components/banner.md'
    - Breadcrumb: 'components/breadcrumb.md'
    - Button: 'components/button.md'
    - Cards:
      - Card Timeline: 'components/cards/card-timeline.md'
    - Checkbox: 'components/checkbox.md'
    - Datepicker: 'components/datepicker.md'
    - Field: 'components/field.md'
    - File Upload: 'components/fileupload.md'
    - Filter: 'components/filter.md'
    - Form: 'components/form.md'
    - List Links: 'components/listlinks.md'
    - List Options: 'components/listoptions.md'
    - Login: 'components/login.md'
    - Page Title: 'components/page-title.md'
    - Pagination: 'components/pagination.md'
    - Quote: 'components/quote.md'
    - Radio: 'components/radio.md'
    - Select: 'components/select.md'
    - Switch: 'components/switch.md'
    - Tables: 'components/tables.md'
    - Toolbar: 'components/toolbar.md'
  - Diretivas:
    - Grid: 'directives/grid.md'
    - Lightbox: 'directives/lightbox.md'
    - Tooltip: 'directives/tooltip.md'
  - Serviços:
    - Modal: 'service/modal.md'
    - Ugla Service: 'service/ugla-service.md'
  - Models:
    - Auth: 'models/auth.md'
    - Checkbox Column Item: 'models/checkbox-column-item.md'
    - Checkbox List Column: 'models/checkbox-list-column.md'
    - Header: 'models/header.md'
    - Link: 'models/link.md'
    - List: 'models/list.md'
    - Menu Item: 'models/menu-item.md'
    - Menu: 'models/menu.md'
    - Options: 'models/options.md'
    - People: 'models/people.md'
    - Select: 'models/select.md'
    - Table Column: 'models/table-column.md'
    - Table Header: 'models/table-header.md'
    - Table Row: 'models/table-row.md'
    - Table: 'models/table.md'

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/ciandt/ugla'
    - type: 'link'
      link: 'https://ugla.dev'
  version: 1.0