name: Documentation

on:
  push:
    branches:
      - master
      - stable
  pull_request:
    branches:
      - master
      - stable
      - '!dependabot/*'

jobs:
  build:
    name: Build MKDocs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8.3
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.3

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Install Mkdocs
      run: pip install mkdocs

    - name: Install Mkdocs Material
      run: pip install mkdocs-material

    - name: Install Pymdown Extensions
      run: pip install pymdown-extensions

    - name: Install Pygments
      run: pip install pygments

    - name: Install Build docs
      run: mkdocs build --verbose --clean --strict

    - name: Deploy on Firebase
      uses: pizzafox/firebase-action@1.0.7
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy